### ISSUE TITLE
Create an IPA file for sideloading it with AltStore

### ISSUE THREAD

**Issue by marcy-97** [valentinegb/Neocat#1]
Hi,
I wanted to ask if it would be possible, that u could create an IPA file with the stickerpack, so that it can be easily sideloaded through something like AltStore.
That would be really nice!

**Comment by valentinegb** [comment]
Sure, I think I can do that!

**Comment by marcy-97** [comment]
Oki, thank you!

**Comment by valentinegb** [comment]
Can you test this `.ipa` and see if it works how it should? I tested on AltStore, which I am using for the first time lol

[neocat.zip](https://github.com/user-attachments/files/17787483/neocat.zip)

(Just change `.zip` to `.ipa`, GitHub wouldn't let me upload it as `.ipa`)

**Comment by marcy-97** [comment]
Hm, it failed with the following message in AltStore:
`Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.valentinegb.Neocat.XQ2PSGY44X" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.valentinegb.Neocat.XQ2PSGY44X, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:isFromSerializedPlaceholder:error:], SourceFileLine=968, NSUnderlyingError=0x9ba364330 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.google.ios.youtube.XQ2PSGY44X.ShareExtension that does not match required prefix of com.valentinegb.Neocat.XQ2PSGY44X. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.google.ios.youtube.XQ2PSGY44X.ShareExtension that does not match required prefix of com.valentinegb.Neocat.XQ2PSGY44X. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1582, NSLocalizedFailureReason=Mismatched bundle IDs.}}}`

**Comment by valentinegb** [comment]
All I know is that seems like an existing issue related to AltStore...

https://github.com/altstoreio/AltStore/issues/1103

**Comment by marcy-97** [comment]
Oh, oki :<
Well, hopefully it gets fixed soon :3

**Comment by valentinegb** [comment]
Sorry :( I'd recommend subscribing to the issue I linked so you can know when that's fixed
Closing this issue though, assuming more people don't start saying they're having the same problem ;-;
